[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan.sepolia]
url = "https://api-sepolia.etherscan.io/api"
key = "18U5Q2NX9TEWXSZ63GHPGDUAKUXTE7KV9T"